services:
  llm:
    container_name: llm
    image: ollama/ollama:latest
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
  db:
    container_name: db
    image: postgres:13
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/tables.sql:/docker-entrypoint-initdb.d/tables.sql