services:
  db:
    container_name: db
    image: postgres:13
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/populate.sql:/docker-entrypoint-initdb.d/populate.sql